/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WriteRouteImport } from './routes/write'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as ArticleEditSlugRouteImport } from './routes/article.edit.$slug'
import { Route as MainArticleSlugRouteImport } from './routes/_main/article/$slug'

const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const ArticleEditSlugRoute = ArticleEditSlugRouteImport.update({
  id: '/article/edit/$slug',
  path: '/article/edit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MainArticleSlugRoute = MainArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => MainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/write': typeof WriteRoute
  '/article/$slug': typeof MainArticleSlugRoute
  '/article/edit/$slug': typeof ArticleEditSlugRoute
}
export interface FileRoutesByTo {
  '/write': typeof WriteRoute
  '/': typeof MainIndexRoute
  '/article/$slug': typeof MainArticleSlugRoute
  '/article/edit/$slug': typeof ArticleEditSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/write': typeof WriteRoute
  '/_main/': typeof MainIndexRoute
  '/_main/article/$slug': typeof MainArticleSlugRoute
  '/article/edit/$slug': typeof ArticleEditSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/write' | '/article/$slug' | '/article/edit/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/write' | '/' | '/article/$slug' | '/article/edit/$slug'
  id:
    | '__root__'
    | '/_main'
    | '/write'
    | '/_main/'
    | '/_main/article/$slug'
    | '/article/edit/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  WriteRoute: typeof WriteRoute
  ArticleEditSlugRoute: typeof ArticleEditSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/article/edit/$slug': {
      id: '/article/edit/$slug'
      path: '/article/edit/$slug'
      fullPath: '/article/edit/$slug'
      preLoaderRoute: typeof ArticleEditSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/article/$slug': {
      id: '/_main/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof MainArticleSlugRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainIndexRoute: typeof MainIndexRoute
  MainArticleSlugRoute: typeof MainArticleSlugRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainIndexRoute: MainIndexRoute,
  MainArticleSlugRoute: MainArticleSlugRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  WriteRoute: WriteRoute,
  ArticleEditSlugRoute: ArticleEditSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
